rule all:
    input: "results/gencode.gtf"


rule download_gencode:
    output: "results/gencode.gtf"
    shell: "wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/gencode.v43.annotation.gtf.gz -O {output}"
