repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: check-added-large-files
    - id: check-toml
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: name-tests-test
    - id: sort-simple-yaml
    - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy
      args: ["--strict",
      "--strict-optional",
      "--warn-unused-configs",
      "--disallow-any-unimported"]
      additional_dependencies: []
      exclude: "(tests/|conftest.py)"
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest
        args: ["tests", "-s"]
        language: system
        pass_filenames: false
        always_run: true
